name: CI
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
          npm install -g bats
      - name: Check dependencies
        run: ./bin/check-deps
      - name: Run shellcheck
        run: shellcheck bin/workon bin/check-deps bin/src/pls-open
      - name: Run tests
        run: bats test/unit/